# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0-rc.2
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ContractDeliverGood(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The details of a delivery contract. Includes the type of good, units needed, and the destination.
    """


    class MetaOapg:
        required = {
            "tradeSymbol",
            "unitsRequired",
            "destinationSymbol",
            "unitsFulfilled",
        }
        
        class properties:
            
            
            class tradeSymbol(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            
            
            class destinationSymbol(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            unitsRequired = schemas.IntSchema
            unitsFulfilled = schemas.IntSchema
            __annotations__ = {
                "tradeSymbol": tradeSymbol,
                "destinationSymbol": destinationSymbol,
                "unitsRequired": unitsRequired,
                "unitsFulfilled": unitsFulfilled,
            }
    
    tradeSymbol: MetaOapg.properties.tradeSymbol
    unitsRequired: MetaOapg.properties.unitsRequired
    destinationSymbol: MetaOapg.properties.destinationSymbol
    unitsFulfilled: MetaOapg.properties.unitsFulfilled
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tradeSymbol"]) -> MetaOapg.properties.tradeSymbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["destinationSymbol"]) -> MetaOapg.properties.destinationSymbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unitsRequired"]) -> MetaOapg.properties.unitsRequired: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["unitsFulfilled"]) -> MetaOapg.properties.unitsFulfilled: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["tradeSymbol", "destinationSymbol", "unitsRequired", "unitsFulfilled", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tradeSymbol"]) -> MetaOapg.properties.tradeSymbol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["destinationSymbol"]) -> MetaOapg.properties.destinationSymbol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unitsRequired"]) -> MetaOapg.properties.unitsRequired: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["unitsFulfilled"]) -> MetaOapg.properties.unitsFulfilled: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["tradeSymbol", "destinationSymbol", "unitsRequired", "unitsFulfilled", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        tradeSymbol: typing.Union[MetaOapg.properties.tradeSymbol, str, ],
        unitsRequired: typing.Union[MetaOapg.properties.unitsRequired, decimal.Decimal, int, ],
        destinationSymbol: typing.Union[MetaOapg.properties.destinationSymbol, str, ],
        unitsFulfilled: typing.Union[MetaOapg.properties.unitsFulfilled, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ContractDeliverGood':
        return super().__new__(
            cls,
            *args,
            tradeSymbol=tradeSymbol,
            unitsRequired=unitsRequired,
            destinationSymbol=destinationSymbol,
            unitsFulfilled=unitsFulfilled,
            _configuration=_configuration,
            **kwargs,
        )
