# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0-rc.2
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ScannedShip(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The ship that was scanned. Details include information about the ship that could be detected by the scanner.
    """


    class MetaOapg:
        required = {
            "symbol",
            "nav",
            "engine",
            "reactor",
            "mounts",
            "registration",
            "frame",
        }
        
        class properties:
            
            
            class symbol(
                schemas.StrSchema
            ):
                pass
        
            @staticmethod
            def registration() -> typing.Type['ShipRegistration']:
                return ShipRegistration
        
            @staticmethod
            def nav() -> typing.Type['ShipNav']:
                return ShipNav
        
            @staticmethod
            def frame() -> typing.Type['ShipFrame']:
                return ShipFrame
        
            @staticmethod
            def reactor() -> typing.Type['ShipReactor']:
                return ShipReactor
        
            @staticmethod
            def engine() -> typing.Type['ShipEngine']:
                return ShipEngine
            
            
            class mounts(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ShipMount']:
                        return ShipMount
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ShipMount'], typing.List['ShipMount']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'mounts':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ShipMount':
                    return super().__getitem__(i)
            __annotations__ = {
                "symbol": symbol,
                "registration": registration,
                "nav": nav,
                "frame": frame,
                "reactor": reactor,
                "engine": engine,
                "mounts": mounts,
            }
    
    symbol: MetaOapg.properties.symbol
    nav: 'ShipNav'
    engine: 'ShipEngine'
    reactor: 'ShipReactor'
    mounts: MetaOapg.properties.mounts
    registration: 'ShipRegistration'
    frame: 'ShipFrame'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["registration"]) -> 'ShipRegistration': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["nav"]) -> 'ShipNav': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["frame"]) -> 'ShipFrame': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["reactor"]) -> 'ShipReactor': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["engine"]) -> 'ShipEngine': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mounts"]) -> MetaOapg.properties.mounts: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["symbol", "registration", "nav", "frame", "reactor", "engine", "mounts", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["registration"]) -> 'ShipRegistration': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["nav"]) -> 'ShipNav': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["frame"]) -> 'ShipFrame': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["reactor"]) -> 'ShipReactor': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["engine"]) -> 'ShipEngine': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mounts"]) -> MetaOapg.properties.mounts: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["symbol", "registration", "nav", "frame", "reactor", "engine", "mounts", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        symbol: typing.Union[MetaOapg.properties.symbol, str, ],
        nav: 'ShipNav',
        engine: 'ShipEngine',
        reactor: 'ShipReactor',
        mounts: typing.Union[MetaOapg.properties.mounts, list, tuple, ],
        registration: 'ShipRegistration',
        frame: 'ShipFrame',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ScannedShip':
        return super().__new__(
            cls,
            *args,
            symbol=symbol,
            nav=nav,
            engine=engine,
            reactor=reactor,
            mounts=mounts,
            registration=registration,
            frame=frame,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.ship_engine import ShipEngine
from openapi_client.model.ship_frame import ShipFrame
from openapi_client.model.ship_mount import ShipMount
from openapi_client.model.ship_nav import ShipNav
from openapi_client.model.ship_reactor import ShipReactor
from openapi_client.model.ship_registration import ShipRegistration
