# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://v2.api.spacetraders.io\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ShipEngine(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The engine determines how quickly a ship travels between waypoints.
    """


    class MetaOapg:
        required = {
            "symbol",
            "requirements",
            "name",
            "description",
            "speed",
        }
        
        class properties:
            
            
            class symbol(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    enum_value_to_name = {
                        "ENGINE_IMPULSE_DRIVE_I": "IMPULSE_DRIVE_I",
                        "ENGINE_ION_DRIVE_I": "ION_DRIVE_I",
                        "ENGINE_ION_DRIVE_II": "ION_DRIVE_II",
                        "ENGINE_HYPER_DRIVE_I": "HYPER_DRIVE_I",
                    }
                
                @schemas.classproperty
                def IMPULSE_DRIVE_I(cls):
                    return cls("ENGINE_IMPULSE_DRIVE_I")
                
                @schemas.classproperty
                def ION_DRIVE_I(cls):
                    return cls("ENGINE_ION_DRIVE_I")
                
                @schemas.classproperty
                def ION_DRIVE_II(cls):
                    return cls("ENGINE_ION_DRIVE_II")
                
                @schemas.classproperty
                def HYPER_DRIVE_I(cls):
                    return cls("ENGINE_HYPER_DRIVE_I")
            name = schemas.StrSchema
            description = schemas.StrSchema
            
            
            class speed(
                schemas.NumberSchema
            ):
            
            
                class MetaOapg:
                    inclusive_minimum = 1
        
            @staticmethod
            def requirements() -> typing.Type['ShipRequirements']:
                return ShipRequirements
        
            @staticmethod
            def condition() -> typing.Type['ShipCondition']:
                return ShipCondition
            __annotations__ = {
                "symbol": symbol,
                "name": name,
                "description": description,
                "speed": speed,
                "requirements": requirements,
                "condition": condition,
            }
    
    symbol: MetaOapg.properties.symbol
    requirements: 'ShipRequirements'
    name: MetaOapg.properties.name
    description: MetaOapg.properties.description
    speed: MetaOapg.properties.speed
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["speed"]) -> MetaOapg.properties.speed: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["requirements"]) -> 'ShipRequirements': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["condition"]) -> 'ShipCondition': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["symbol", "name", "description", "speed", "requirements", "condition", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["speed"]) -> MetaOapg.properties.speed: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["requirements"]) -> 'ShipRequirements': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["condition"]) -> typing.Union['ShipCondition', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["symbol", "name", "description", "speed", "requirements", "condition", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        symbol: typing.Union[MetaOapg.properties.symbol, str, ],
        requirements: 'ShipRequirements',
        name: typing.Union[MetaOapg.properties.name, str, ],
        description: typing.Union[MetaOapg.properties.description, str, ],
        speed: typing.Union[MetaOapg.properties.speed, decimal.Decimal, int, float, ],
        condition: typing.Union['ShipCondition', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ShipEngine':
        return super().__new__(
            cls,
            *args,
            symbol=symbol,
            requirements=requirements,
            name=name,
            description=description,
            speed=speed,
            condition=condition,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.ship_condition import ShipCondition
from openapi_client.model.ship_requirements import ShipRequirements
