# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0-rc.2
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ShipType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "SHIP_PROBE": "PROBE",
            "SHIP_MINING_DRONE": "MINING_DRONE",
            "SHIP_INTERCEPTOR": "INTERCEPTOR",
            "SHIP_LIGHT_HAULER": "LIGHT_HAULER",
            "SHIP_COMMAND_FRIGATE": "COMMAND_FRIGATE",
            "SHIP_EXPLORER": "EXPLORER",
            "SHIP_HEAVY_FREIGHTER": "HEAVY_FREIGHTER",
            "SHIP_LIGHT_SHUTTLE": "LIGHT_SHUTTLE",
            "SHIP_ORE_HOUND": "ORE_HOUND",
        }
    
    @schemas.classproperty
    def PROBE(cls):
        return cls("SHIP_PROBE")
    
    @schemas.classproperty
    def MINING_DRONE(cls):
        return cls("SHIP_MINING_DRONE")
    
    @schemas.classproperty
    def INTERCEPTOR(cls):
        return cls("SHIP_INTERCEPTOR")
    
    @schemas.classproperty
    def LIGHT_HAULER(cls):
        return cls("SHIP_LIGHT_HAULER")
    
    @schemas.classproperty
    def COMMAND_FRIGATE(cls):
        return cls("SHIP_COMMAND_FRIGATE")
    
    @schemas.classproperty
    def EXPLORER(cls):
        return cls("SHIP_EXPLORER")
    
    @schemas.classproperty
    def HEAVY_FREIGHTER(cls):
        return cls("SHIP_HEAVY_FREIGHTER")
    
    @schemas.classproperty
    def LIGHT_SHUTTLE(cls):
        return cls("SHIP_LIGHT_SHUTTLE")
    
    @schemas.classproperty
    def ORE_HOUND(cls):
        return cls("SHIP_ORE_HOUND")
