# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0-rc.2
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ShipMount(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    A mount is installed on the exterier of a ship.
    """


    class MetaOapg:
        required = {
            "symbol",
            "requirements",
            "name",
        }
        
        class properties:
            
            
            class symbol(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def GAS_SIPHON_I(cls):
                    return cls("MOUNT_GAS_SIPHON_I")
                
                @schemas.classproperty
                def GAS_SIPHON_II(cls):
                    return cls("MOUNT_GAS_SIPHON_II")
                
                @schemas.classproperty
                def GAS_SIPHON_III(cls):
                    return cls("MOUNT_GAS_SIPHON_III")
                
                @schemas.classproperty
                def SENSOR_ARRAY_I(cls):
                    return cls("MOUNT_SENSOR_ARRAY_I")
                
                @schemas.classproperty
                def SENSOR_ARRAY_II(cls):
                    return cls("MOUNT_SENSOR_ARRAY_II")
                
                @schemas.classproperty
                def SENSOR_ARRAY_III(cls):
                    return cls("MOUNT_SENSOR_ARRAY_III")
                
                @schemas.classproperty
                def MINING_LASER_I(cls):
                    return cls("MOUNT_MINING_LASER_I")
                
                @schemas.classproperty
                def MINING_LASER_II(cls):
                    return cls("MOUNT_MINING_LASER_II")
                
                @schemas.classproperty
                def MINING_LASER_III(cls):
                    return cls("MOUNT_MINING_LASER_III")
                
                @schemas.classproperty
                def LASER_CANNON_I(cls):
                    return cls("MOUNT_LASER_CANNON_I")
                
                @schemas.classproperty
                def MISSILE_LAUNCHER_I(cls):
                    return cls("MOUNT_MISSILE_LAUNCHER_I")
                
                @schemas.classproperty
                def TURRET_I(cls):
                    return cls("MOUNT_TURRET_I")
            name = schemas.StrSchema
        
            @staticmethod
            def requirements() -> typing.Type['ShipRequirements']:
                return ShipRequirements
            description = schemas.StrSchema
            
            
            class strength(
                schemas.IntSchema
            ):
                pass
            __annotations__ = {
                "symbol": symbol,
                "name": name,
                "requirements": requirements,
                "description": description,
                "strength": strength,
            }
    
    symbol: MetaOapg.properties.symbol
    requirements: 'ShipRequirements'
    name: MetaOapg.properties.name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["requirements"]) -> 'ShipRequirements': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["description"]) -> MetaOapg.properties.description: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["strength"]) -> MetaOapg.properties.strength: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["symbol", "name", "requirements", "description", "strength", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["symbol"]) -> MetaOapg.properties.symbol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["requirements"]) -> 'ShipRequirements': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["description"]) -> typing.Union[MetaOapg.properties.description, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["strength"]) -> typing.Union[MetaOapg.properties.strength, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["symbol", "name", "requirements", "description", "strength", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        symbol: typing.Union[MetaOapg.properties.symbol, str, ],
        requirements: 'ShipRequirements',
        name: typing.Union[MetaOapg.properties.name, str, ],
        description: typing.Union[MetaOapg.properties.description, str, schemas.Unset] = schemas.unset,
        strength: typing.Union[MetaOapg.properties.strength, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ShipMount':
        return super().__new__(
            cls,
            *args,
            symbol=symbol,
            requirements=requirements,
            name=name,
            description=description,
            strength=strength,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.ship_requirements import ShipRequirements
