# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0-rc.2
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class ShipNav(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The navigation information of the ship.
    """


    class MetaOapg:
        required = {
            "route",
            "systemSymbol",
            "waypointSymbol",
            "flightMode",
            "status",
        }
        
        class properties:
            systemSymbol = schemas.StrSchema
            waypointSymbol = schemas.StrSchema
        
            @staticmethod
            def route() -> typing.Type['ShipNavRoute']:
                return ShipNavRoute
        
            @staticmethod
            def status() -> typing.Type['ShipNavStatus']:
                return ShipNavStatus
        
            @staticmethod
            def flightMode() -> typing.Type['ShipNavFlightMode']:
                return ShipNavFlightMode
            __annotations__ = {
                "systemSymbol": systemSymbol,
                "waypointSymbol": waypointSymbol,
                "route": route,
                "status": status,
                "flightMode": flightMode,
            }
    
    route: 'ShipNavRoute'
    systemSymbol: MetaOapg.properties.systemSymbol
    waypointSymbol: MetaOapg.properties.waypointSymbol
    flightMode: 'ShipNavFlightMode'
    status: 'ShipNavStatus'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["systemSymbol"]) -> MetaOapg.properties.systemSymbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["waypointSymbol"]) -> MetaOapg.properties.waypointSymbol: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["route"]) -> 'ShipNavRoute': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> 'ShipNavStatus': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["flightMode"]) -> 'ShipNavFlightMode': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["systemSymbol", "waypointSymbol", "route", "status", "flightMode", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["systemSymbol"]) -> MetaOapg.properties.systemSymbol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["waypointSymbol"]) -> MetaOapg.properties.waypointSymbol: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["route"]) -> 'ShipNavRoute': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> 'ShipNavStatus': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["flightMode"]) -> 'ShipNavFlightMode': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["systemSymbol", "waypointSymbol", "route", "status", "flightMode", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        route: 'ShipNavRoute',
        systemSymbol: typing.Union[MetaOapg.properties.systemSymbol, str, ],
        waypointSymbol: typing.Union[MetaOapg.properties.waypointSymbol, str, ],
        flightMode: 'ShipNavFlightMode',
        status: 'ShipNavStatus',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ShipNav':
        return super().__new__(
            cls,
            *args,
            route=route,
            systemSymbol=systemSymbol,
            waypointSymbol=waypointSymbol,
            flightMode=flightMode,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )

from openapi_client.model.ship_nav_flight_mode import ShipNavFlightMode
from openapi_client.model.ship_nav_route import ShipNavRoute
from openapi_client.model.ship_nav_status import ShipNavStatus
