# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://api-server-2-0-0-rc-2-vxxwq5xqdq-uc.a.run.app\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0-rc.2
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from openapi_client import schemas  # noqa: F401


class WaypointType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    The type of waypoint.
    """
    
    @schemas.classproperty
    def PLANET(cls):
        return cls("PLANET")
    
    @schemas.classproperty
    def GAS_GIANT(cls):
        return cls("GAS_GIANT")
    
    @schemas.classproperty
    def MOON(cls):
        return cls("MOON")
    
    @schemas.classproperty
    def ORBITAL_STATION(cls):
        return cls("ORBITAL_STATION")
    
    @schemas.classproperty
    def JUMP_GATE(cls):
        return cls("JUMP_GATE")
    
    @schemas.classproperty
    def ASTEROID_FIELD(cls):
        return cls("ASTEROID_FIELD")
    
    @schemas.classproperty
    def NEBULA(cls):
        return cls("NEBULA")
    
    @schemas.classproperty
    def DEBRIS_FIELD(cls):
        return cls("DEBRIS_FIELD")
    
    @schemas.classproperty
    def GRAVITY_WELL(cls):
        return cls("GRAVITY_WELL")
