# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is a multiplayer sci-fi strategy game where you acquire and manage a fleet of ships across a growing and dynamic universe.  Similar to games such as Eve Online, you work with or against other players to establish trade routes, chart new systems, mine precious ores, patrol for pirates, spy on factions, and discover hidden treasures.  SpaceTraders as a game is unique in that it is entirely accessible through open and well-documented API endpoints.  If this sounds fun and interesting to you, please drop into our Discord and get to know the community. We are actively working on new clients, new ideas and sharing tips for how to play the game.   ```json http {   \"method\": \"GET\",   \"url\": \"https://v2.api.spacetraders.io\", } ```  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.my_ships_ship_symbol_chart.post import CreateChart
from openapi_client.paths.my_ships_ship_symbol_scan_ships.post import CreateShipShipScan
from openapi_client.paths.my_ships_ship_symbol_scan_systems.post import CreateShipSystemScan
from openapi_client.paths.my_ships_ship_symbol_survey.post import CreateSurvey
from openapi_client.paths.my_ships_ship_symbol_dock.post import DockShip
from openapi_client.paths.my_ships_ship_symbol_extract.post import ExtractResources
from openapi_client.paths.my_ships_ship_symbol.get import GetMyShip
from openapi_client.paths.my_ships.get import GetMyShips
from openapi_client.paths.my_ships_ship_symbol_cooldown.get import GetShipCooldown
from openapi_client.paths.my_ships_ship_symbol_jettison.post import Jettison
from openapi_client.paths.my_ships_ship_symbol_jump.post import JumpShip
from openapi_client.paths.my_ships_ship_symbol_navigate.post import NavigateShip
from openapi_client.paths.my_ships_ship_symbol_orbit.post import OrbitShip
from openapi_client.paths.my_ships_ship_symbol_purchase.post import PurchaseCargo
from openapi_client.paths.my_ships.post import PurchaseShip
from openapi_client.paths.my_ships_ship_symbol_refuel.post import RefuelShip
from openapi_client.paths.my_ships_ship_symbol_sell.post import SellCargo
from openapi_client.paths.my_ships_ship_symbol_refine.post import ShipRefine
from openapi_client.paths.my_ships_ship_symbol_transfer.post import TransferCargo
from openapi_client.paths.my_ships_ship_symbol_warp.post import WarpShip


class FleetApi(
    CreateChart,
    CreateShipShipScan,
    CreateShipSystemScan,
    CreateSurvey,
    DockShip,
    ExtractResources,
    GetMyShip,
    GetMyShips,
    GetShipCooldown,
    Jettison,
    JumpShip,
    NavigateShip,
    OrbitShip,
    PurchaseCargo,
    PurchaseShip,
    RefuelShip,
    SellCargo,
    ShipRefine,
    TransferCargo,
    WarpShip,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
